title: My Blog
author: √Åine Phelan
email: your-email@domain.com
description: # this means to ignore newlines until "baseurl:"
  A blog for Aine Phelan to communicate experiences and insights on her life, data science journey etc.
  
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-time-machine
